import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import { Inter } from "next/font/google";
import BootstrapClient from "@/components/BootstrapClient.js";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Popup from "@/components/Popup";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Banao | Utkarsh Kushwaha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Popup />
        <NavBar />
        {children}
        <Footer />
        <BootstrapClient />
      </body>
    </html>
  );
}
